/*
 * @file test/decoder_test.c
 * @brief Milestone 13.4 correctness gate: wasmtime CLI driver for
 * cognition's compiled VITS decoder.
 *
 * Sibling of `test/encoder_test.c` — same flow, different graph:
 *
 *   1. Kernel-registration list comes from `decoder_kernels_stub.c`
 *      (autogenerated by test/gen_kernel_stub.py from lib0.o's nm
 *      output). The decoder has more TIR kernels than the encoder —
 *      ConvTranspose upsample dominates — and hand-listing is not
 *      practical.
 *   2. Inputs are two positional tensors (z_p float32[1,128,1024],
 *      y_mask float32[1,1,1024]) read from bin files the Python side
 *      (test/compile_decoder_wasm.py) wrote next to this executable's
 *      WASI preopen.
 *   3. Output is a single positional waveform tensor
 *      (float32[1,1,262144]) read via `RelaxVirtualMachineGetOutput`
 *      and dumped into `wasm_waveform.bin` for the Python-side diff.
 *
 * The gen_kernel_stub.py helper emits its C stub with symbol
 * `register_all_encoder_kernels()`. We reuse it — the name is
 * historical, not decoder/encoder-specific — via a forward
 * declaration under a locally aliased name below.
 */

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <dlpack/dlpack.h>
#include <relax_vm.h>

/* Provided by devc.o via its C++ constructor before main(). */
/* Registration is now done inside register_all_dec_kernels() which
 * also registers the dec-prefixed library_ctx slot via
 * gen_kernel_stub.py's --sys-lib-prefix path. */

/* From decoder_kernels_stub.c (autogenerated). gen_kernel_stub.py
 * hardcodes the function name `register_all_encoder_kernels` — that
 * name is historical (the stub is model-agnostic) so we just extern
 * it under the same name here. */
extern int register_all_dec_kernels(void);

extern int TVMBackendRegisterSystemLibSymbol(const char *name, void *ptr);
extern const char *TVMGetLastError(void);

#define RUN(_expr, _msg)                                                                           \
    do {                                                                                           \
        int _status = (_expr);                                                                     \
        if (_status != 0) {                                                                        \
            fprintf(stderr, "[decoder_test] %s failed status=%d err=%s\n", _msg, _status,          \
                    TVMGetLastError() ? TVMGetLastError() : "(null)");                             \
            return _status;                                                                        \
        }                                                                                          \
    } while (0)

static int read_all(const char *path, void *buf, size_t bytes) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "[decoder_test] cannot open %s: %s\n", path, strerror(errno));
        return -1;
    }
    size_t got = fread(buf, 1, bytes, fp);
    fclose(fp);
    if (got != bytes) {
        fprintf(stderr, "[decoder_test] short read %s: %zu/%zu\n", path, got, bytes);
        return -1;
    }
    return 0;
}

static int write_all(const char *path, const void *buf, size_t bytes) {
    FILE *fp = fopen(path, "wb");
    if (!fp) {
        fprintf(stderr, "[decoder_test] cannot open %s for write: %s\n", path, strerror(errno));
        return -1;
    }
    size_t put = fwrite(buf, 1, bytes, fp);
    fclose(fp);
    if (put != bytes) {
        fprintf(stderr, "[decoder_test] short write %s: %zu/%zu\n", path, put, bytes);
        return -1;
    }
    return 0;
}

/* Decoder-specific shapes — must match test/compile_decoder_wasm.py's
 * FRAME_COUNT / Z_CHANNELS and the fixed upsample product from the
 * nano config (8*8*2*2 = 256 -> waveform samples per frame). */
#define FRAME_COUNT 1024
#define Z_CHANNELS 128
#define UPSAMPLE_RATIO 256
#define WAVEFORM_SAMPLES (FRAME_COUNT * UPSAMPLE_RATIO) /* 262144 */

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <dir-with-decoder_out-files>\n", argv[0]);
        return 2;
    }
    const char *dir = argv[1];
    char path[1024];

    static float z_p[1 * Z_CHANNELS * FRAME_COUNT];
    static float y_mask[1 * 1 * FRAME_COUNT];

    snprintf(path, sizeof(path), "%s/z_p.bin", dir);
    RUN(read_all(path, z_p, sizeof(z_p)), "read z_p.bin");
    snprintf(path, sizeof(path), "%s/y_mask.bin", dir);
    RUN(read_all(path, y_mask, sizeof(y_mask)), "read y_mask.bin");

    /*
     * Register library_ctx (module handle slot) and every TIR kernel.
     * devc.o's ctor already registered __tvm_ffi__library_bin before main().
     */
    RUN(register_all_dec_kernels(), "register decoder kernels + dec_library_ctx");

    DLDevice cpu = {kDLCPU, 0};
    DLDataType f32 = {kDLFloat, 32, 1};

    int64_t z_p_shape[3] = {1, Z_CHANNELS, FRAME_COUNT};
    int64_t y_mask_shape[3] = {1, 1, FRAME_COUNT};

    DLTensor z_p_t = {.data = z_p, .device = cpu, .ndim = 3, .dtype = f32,
                      .shape = z_p_shape, .strides = NULL, .byte_offset = 0};
    DLTensor y_mask_t = {.data = y_mask, .device = cpu, .ndim = 3, .dtype = f32,
                         .shape = y_mask_shape, .strides = NULL, .byte_offset = 0};

    fprintf(stderr, "[decoder_test] creating VM\n");
    TVM_RT_WASM_RelaxVirtualMachine vm =
        TVM_RT_WASM_RelaxVirtualMachineCreateWithPrefix("dec_", &cpu, 1);
    if (!vm) {
        fprintf(stderr, "[decoder_test] VM create failed: %s\n",
                TVMGetLastError() ? TVMGetLastError() : "(null)");
        return 1;
    }

    int n_in = TVM_RT_WASM_RelaxVirtualMachineGetNumInputs(vm, NULL);
    fprintf(stderr, "[decoder_test] main() num_inputs=%d\n", n_in);

    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 0, &z_p_t), "set input 0 (z_p)");
    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 1, &y_mask_t), "set input 1 (y_mask)");
    fprintf(stderr, "[decoder_test] running main()\n");
    RUN(TVM_RT_WASM_RelaxVirtualMachineRun(vm, NULL), "run main");

    /*
     * Output (single tensor — decoder-io.json's output_order is
     * ["waveform"]):
     *   0: waveform  f32 [1, 1, 262144]
     */
    int64_t waveform_shape[3] = {1, 1, WAVEFORM_SAMPLES};
    static float waveform[1 * 1 * WAVEFORM_SAMPLES];

    DLTensor waveform_t = {.data = waveform, .device = cpu, .ndim = 3, .dtype = f32,
                           .shape = waveform_shape, .strides = NULL, .byte_offset = 0};

    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 0, &waveform_t), "get output 0");

    snprintf(path, sizeof(path), "%s/wasm_waveform.bin", dir);
    RUN(write_all(path, waveform, sizeof(waveform)), "write waveform");

    fprintf(stderr, "[decoder_test] first waveform values: %.6f %.6f %.6f %.6f\n",
            waveform[0], waveform[1], waveform[2], waveform[3]);

    TVM_RT_WASM_RelaxVirtualMachineFree(vm);
    return 0;
}
