/*
 * @file test/encoder_webgpu_test.c
 * @brief Milestone 14.6b correctness gate: WebGPU-target sibling of
 * `test/encoder_test.c` for cognition's rewritten VITS encoder ONNX.
 *
 * Structural mirror of the CPU encoder driver (M13.3) with the same
 * two-device VM setup toy_webgpu_test.c / decoder_webgpu_test.c use:
 *
 *   1. Kernel-registration list comes from `encoder_webgpu_kernels_stub.c`
 *      (autogenerated by test/gen_kernel_stub.py from lib0.o's nm output).
 *   2. Inputs are three positional tensors (tokens uint32[1,256],
 *      lengths int32[1], length_scale float32[]) read from bin files
 *      the Python side (test/compile_encoder_webgpu.py) wrote next to
 *      this executable's WASI preopen. Input dtypes were flipped at
 *      M14.6b from int64/int64/float32 to eliminate int64 from the
 *      graph so TVM's WGSL codegen (no i64 support) can lower every
 *      device PrimFunc.
 *   3. Outputs are three positional tensors read via
 *      `RelaxVirtualMachineGetOutput` and dumped into `wasm_<name>.bin`
 *      alongside the oracle files. The Node-side driver diffs each
 *      against `oracle_<name>.bin`.
 *   4. VM device list includes kDLWebGPU at index 0 alongside kDLCPU at
 *      index 1 — matches toy_webgpu_test.c / decoder_webgpu_test.c so
 *      alloc_storage instructions compiled with device_index=0 land on
 *      WebGPU.
 *   5. Runs under Node + JSPI (not wasmtime): cognition's
 *      `web/test/encoder-webgpu.test.mjs` instantiates this wasm binary
 *      and satisfies `host:webgpu` via `web/src/adopt/webgpu-host-impl.js`.
 */

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <dlpack/dlpack.h>
#include <relax_vm.h>

extern int register_all_enc_kernels(void);

extern int TVMBackendRegisterSystemLibSymbol(const char *name, void *ptr);
extern const char *TVMGetLastError(void);

#define RUN(_expr, _msg)                                                                           \
    do {                                                                                           \
        int _status = (_expr);                                                                     \
        if (_status != 0) {                                                                        \
            fprintf(stderr, "[encoder_webgpu_test] %s failed status=%d err=%s\n", _msg, _status,   \
                    TVMGetLastError() ? TVMGetLastError() : "(null)");                             \
            return _status;                                                                        \
        }                                                                                          \
    } while (0)

static int read_all(const char *path, void *buf, size_t bytes) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "[encoder_webgpu_test] cannot open %s: %s\n", path, strerror(errno));
        return -1;
    }
    size_t got = fread(buf, 1, bytes, fp);
    fclose(fp);
    if (got != bytes) {
        fprintf(stderr, "[encoder_webgpu_test] short read %s: %zu/%zu\n", path, got, bytes);
        return -1;
    }
    return 0;
}

static int write_all(const char *path, const void *buf, size_t bytes) {
    FILE *fp = fopen(path, "wb");
    if (!fp) {
        fprintf(stderr, "[encoder_webgpu_test] cannot open %s for write: %s\n", path,
                strerror(errno));
        return -1;
    }
    size_t put = fwrite(buf, 1, bytes, fp);
    fclose(fp);
    if (put != bytes) {
        fprintf(stderr, "[encoder_webgpu_test] short write %s: %zu/%zu\n", path, put, bytes);
        return -1;
    }
    return 0;
}

/* Must match test/compile_encoder_webgpu.py's TOKEN_COUNT / FRAME_COUNT. */
#define TOKEN_COUNT 256
#define FRAME_COUNT 1024
#define M_P_CHANNELS 128

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <dir-with-encoder_webgpu_out-files>\n", argv[0]);
        return 2;
    }
    const char *dir = argv[1];
    char path[1024];

    /* Post-M14.6b input dtypes — see file header + compile probe. */
    static uint32_t tokens[1 * TOKEN_COUNT];
    static int32_t lengths[1];
    static float length_scale;

    snprintf(path, sizeof(path), "%s/tokens.bin", dir);
    RUN(read_all(path, tokens, sizeof(tokens)), "read tokens.bin");
    snprintf(path, sizeof(path), "%s/lengths.bin", dir);
    RUN(read_all(path, lengths, sizeof(lengths)), "read lengths.bin");
    snprintf(path, sizeof(path), "%s/length_scale.bin", dir);
    RUN(read_all(path, &length_scale, sizeof(length_scale)), "read length_scale.bin");

    /*
     * Register library_ctx (module handle slot) and every TIR kernel.
     * devc.o's ctor already registered __tvm_ffi__library_bin before main().
     */
    RUN(register_all_enc_kernels(), "register encoder kernels + enc_library_ctx");

    /* CPU host tensors — the VM copies these into WebGPU device memory
     * as part of SetInput (RelaxVM_CopyTensorToRegister allocates a
     * matching GPU buffer + WGPU_MemoryCopyHtoD); readback happens
     * during GetOutput via WGPU_MemoryCopyDtoH. Mirrors
     * toy_webgpu_test.c / decoder_webgpu_test.c — same 14.5b fix
     * (`26c839b`). */
    DLDevice cpu = {kDLCPU, 0};
    DLDevice gpu = {kDLWebGPU, 0};
    DLDataType u32 = {kDLUInt, 32, 1};
    DLDataType i32 = {kDLInt, 32, 1};
    DLDataType f32 = {kDLFloat, 32, 1};

    int64_t tokens_shape[2] = {1, TOKEN_COUNT};
    int64_t lengths_shape[1] = {1};

    DLTensor tokens_t = {.data = tokens, .device = cpu, .ndim = 2, .dtype = u32,
                         .shape = tokens_shape, .strides = NULL, .byte_offset = 0};
    DLTensor lengths_t = {.data = lengths, .device = cpu, .ndim = 1, .dtype = i32,
                          .shape = lengths_shape, .strides = NULL, .byte_offset = 0};
    DLTensor length_scale_t = {.data = &length_scale, .device = cpu, .ndim = 0, .dtype = f32,
                               .shape = NULL, .strides = NULL, .byte_offset = 0};

    fprintf(stderr, "[encoder_webgpu_test] creating VM (system library, WebGPU device)\n");
    /* Two-device list, WebGPU at index 0 (primary compute device the
     * compiled bytecode's alloc-storage instructions target) and CPU
     * at index 1 for host-side helpers. Same convention toy_webgpu_test.c
     * uses. sys-lib module carries the `enc_` prefix — reuses
     * CreateWithPrefix from encoder_test.c. */
    DLDevice dev_list[2] = {gpu, cpu};
    TVM_RT_WASM_RelaxVirtualMachine vm =
        TVM_RT_WASM_RelaxVirtualMachineCreateWithPrefix("enc_", dev_list, 2);
    if (!vm) {
        fprintf(stderr, "[encoder_webgpu_test] VM create failed: %s\n",
                TVMGetLastError() ? TVMGetLastError() : "(null)");
        return 1;
    }

    int n_in = TVM_RT_WASM_RelaxVirtualMachineGetNumInputs(vm, NULL);
    fprintf(stderr, "[encoder_webgpu_test] main() num_inputs=%d\n", n_in);

    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 0, &tokens_t), "set input 0 (tokens)");
    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 1, &lengths_t), "set input 1 (lengths)");
    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 2, &length_scale_t),
        "set input 2 (length_scale)");
    fprintf(stderr, "[encoder_webgpu_test] running main()\n");
    RUN(TVM_RT_WASM_RelaxVirtualMachineRun(vm, NULL), "run main");

    /*
     * Outputs (order matches encoder-io.json's `output_order` — same as the
     * ONNX graph's output list):
     *   0: m_p_expanded       f32 [1, 128, 1024]
     *   1: logs_p_expanded    f32 [1, 128, 1024]
     *   2: y_mask             f32 [1, 1,   1024]
     */
    int64_t m_p_shape[3] = {1, M_P_CHANNELS, FRAME_COUNT};
    int64_t y_mask_shape[3] = {1, 1, FRAME_COUNT};

    static float m_p_expanded[1 * M_P_CHANNELS * FRAME_COUNT];
    static float logs_p_expanded[1 * M_P_CHANNELS * FRAME_COUNT];
    static float y_mask[1 * 1 * FRAME_COUNT];

    DLTensor m_p_t = {.data = m_p_expanded, .device = cpu, .ndim = 3, .dtype = f32,
                      .shape = m_p_shape, .strides = NULL, .byte_offset = 0};
    DLTensor logs_p_t = {.data = logs_p_expanded, .device = cpu, .ndim = 3, .dtype = f32,
                         .shape = m_p_shape, .strides = NULL, .byte_offset = 0};
    DLTensor y_mask_t = {.data = y_mask, .device = cpu, .ndim = 3, .dtype = f32,
                         .shape = y_mask_shape, .strides = NULL, .byte_offset = 0};

    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 0, &m_p_t), "get output 0");
    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 1, &logs_p_t), "get output 1");
    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 2, &y_mask_t), "get output 2");

    snprintf(path, sizeof(path), "%s/wasm_m_p_expanded.bin", dir);
    RUN(write_all(path, m_p_expanded, sizeof(m_p_expanded)), "write m_p_expanded");
    snprintf(path, sizeof(path), "%s/wasm_logs_p_expanded.bin", dir);
    RUN(write_all(path, logs_p_expanded, sizeof(logs_p_expanded)), "write logs_p_expanded");
    snprintf(path, sizeof(path), "%s/wasm_y_mask.bin", dir);
    RUN(write_all(path, y_mask, sizeof(y_mask)), "write y_mask");

    fprintf(stderr, "[encoder_webgpu_test] first m_p values: %.6f %.6f %.6f %.6f\n",
            m_p_expanded[0], m_p_expanded[1], m_p_expanded[2], m_p_expanded[3]);
    fprintf(stderr, "[encoder_webgpu_test] first y_mask values: %.6f %.6f %.6f %.6f\n",
            y_mask[0], y_mask[1], y_mask[2], y_mask[3]);

    TVM_RT_WASM_RelaxVirtualMachineFree(vm);
    return 0;
}
