/*
 * @file test/encoder_test.c
 * @brief Milestone 13.3 correctness gate: wasmtime CLI driver for
 * cognition's compiled VITS encoder.
 *
 * Flow mirrors the toy driver (test/toy_relax.c) — same devc.o + lib0.o
 * pattern the fork's system_library.c consumes — except:
 *
 *   1. Kernel-registration list comes from `encoder_kernels_stub.c`
 *      (autogenerated by test/gen_kernel_stub.py from lib0.o's nm
 *      output). ~100 kernels is too many to hand-list.
 *   2. Inputs are three positional tensors (tokens int64[1,256],
 *      lengths int64[1], length_scale float32[]) read from bin files
 *      the Python side wrote next to this executable's WASI preopen.
 *   3. Outputs are three positional tensors read via
 *      `RelaxVirtualMachineGetOutput` and dumped into
 *      `wasm_<name>.bin` alongside the oracle files. The Python side
 *      diffs each against `oracle_<name>.bin`.
 */

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <dlpack/dlpack.h>
#include <relax_vm.h>

/* Provided by devc.o via its C++ constructor before main(). */
/* Registration is now done inside register_all_enc_kernels() which
 * also registers the enc-prefixed library_ctx slot via
 * gen_kernel_stub.py's --sys-lib-prefix path. */

/* From encoder_kernels_stub.c (autogenerated). */
extern int register_all_enc_kernels(void);

extern int TVMBackendRegisterSystemLibSymbol(const char *name, void *ptr);
extern const char *TVMGetLastError(void);

#define RUN(_expr, _msg)                                                                           \
    do {                                                                                           \
        int _status = (_expr);                                                                     \
        if (_status != 0) {                                                                        \
            fprintf(stderr, "[encoder_test] %s failed status=%d err=%s\n", _msg, _status,          \
                    TVMGetLastError() ? TVMGetLastError() : "(null)");                             \
            return _status;                                                                        \
        }                                                                                          \
    } while (0)

static int read_all(const char *path, void *buf, size_t bytes) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "[encoder_test] cannot open %s: %s\n", path, strerror(errno));
        return -1;
    }
    size_t got = fread(buf, 1, bytes, fp);
    fclose(fp);
    if (got != bytes) {
        fprintf(stderr, "[encoder_test] short read %s: %zu/%zu\n", path, got, bytes);
        return -1;
    }
    return 0;
}

static int write_all(const char *path, const void *buf, size_t bytes) {
    FILE *fp = fopen(path, "wb");
    if (!fp) {
        fprintf(stderr, "[encoder_test] cannot open %s for write: %s\n", path, strerror(errno));
        return -1;
    }
    size_t put = fwrite(buf, 1, bytes, fp);
    fclose(fp);
    if (put != bytes) {
        fprintf(stderr, "[encoder_test] short write %s: %zu/%zu\n", path, put, bytes);
        return -1;
    }
    return 0;
}

/* Encoder-specific shapes — must match test/compile_encoder_wasm.py's TOKEN_COUNT / FRAME_COUNT. */
#define TOKEN_COUNT 256
#define FRAME_COUNT 1024
#define M_P_CHANNELS 128

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <dir-with-encoder_out-files>\n", argv[0]);
        return 2;
    }
    const char *dir = argv[1];
    char path[1024];

    static int64_t tokens[1 * TOKEN_COUNT];
    static int64_t lengths[1];
    static float length_scale;

    snprintf(path, sizeof(path), "%s/tokens.bin", dir);
    RUN(read_all(path, tokens, sizeof(tokens)), "read tokens.bin");
    snprintf(path, sizeof(path), "%s/lengths.bin", dir);
    RUN(read_all(path, lengths, sizeof(lengths)), "read lengths.bin");
    snprintf(path, sizeof(path), "%s/length_scale.bin", dir);
    RUN(read_all(path, &length_scale, sizeof(length_scale)), "read length_scale.bin");

    /*
     * Register library_ctx (module handle slot) and every TIR kernel.
     * devc.o's ctor already registered __tvm_ffi__library_bin before main().
     */
    RUN(register_all_enc_kernels(), "register encoder kernels + enc_library_ctx");

    DLDevice cpu = {kDLCPU, 0};
    DLDataType i64 = {kDLInt, 64, 1};
    DLDataType f32 = {kDLFloat, 32, 1};

    int64_t tokens_shape[2] = {1, TOKEN_COUNT};
    int64_t lengths_shape[1] = {1};
    /* length_scale is a rank-0 scalar per ONNX / graph-io.json. */

    DLTensor tokens_t = {.data = tokens, .device = cpu, .ndim = 2, .dtype = i64,
                         .shape = tokens_shape, .strides = NULL, .byte_offset = 0};
    DLTensor lengths_t = {.data = lengths, .device = cpu, .ndim = 1, .dtype = i64,
                          .shape = lengths_shape, .strides = NULL, .byte_offset = 0};
    DLTensor length_scale_t = {.data = &length_scale, .device = cpu, .ndim = 0, .dtype = f32,
                               .shape = NULL, .strides = NULL, .byte_offset = 0};

    fprintf(stderr, "[encoder_test] creating VM\n");
    TVM_RT_WASM_RelaxVirtualMachine vm =
        TVM_RT_WASM_RelaxVirtualMachineCreateWithPrefix("enc_", &cpu, 1);
    if (!vm) {
        fprintf(stderr, "[encoder_test] VM create failed: %s\n",
                TVMGetLastError() ? TVMGetLastError() : "(null)");
        return 1;
    }

    int n_in = TVM_RT_WASM_RelaxVirtualMachineGetNumInputs(vm, NULL);
    fprintf(stderr, "[encoder_test] main() num_inputs=%d\n", n_in);

    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 0, &tokens_t), "set input 0 (tokens)");
    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 1, &lengths_t), "set input 1 (lengths)");
    RUN(TVM_RT_WASM_RelaxVirtualMachineSetInput(vm, NULL, 2, &length_scale_t),
        "set input 2 (length_scale)");
    fprintf(stderr, "[encoder_test] running main()\n");
    RUN(TVM_RT_WASM_RelaxVirtualMachineRun(vm, NULL), "run main");

    /*
     * Outputs (order matches encoder-io.json's `output_order` — same as the
     * ONNX graph's output list):
     *   0: m_p_expanded       f32 [1, 128, 1024]
     *   1: logs_p_expanded    f32 [1, 128, 1024]
     *   2: y_mask             f32 [1, 1,   1024]
     */
    int64_t m_p_shape[3] = {1, M_P_CHANNELS, FRAME_COUNT};
    int64_t y_mask_shape[3] = {1, 1, FRAME_COUNT};

    static float m_p_expanded[1 * M_P_CHANNELS * FRAME_COUNT];
    static float logs_p_expanded[1 * M_P_CHANNELS * FRAME_COUNT];
    static float y_mask[1 * 1 * FRAME_COUNT];

    DLTensor m_p_t = {.data = m_p_expanded, .device = cpu, .ndim = 3, .dtype = f32,
                      .shape = m_p_shape, .strides = NULL, .byte_offset = 0};
    DLTensor logs_p_t = {.data = logs_p_expanded, .device = cpu, .ndim = 3, .dtype = f32,
                         .shape = m_p_shape, .strides = NULL, .byte_offset = 0};
    DLTensor y_mask_t = {.data = y_mask, .device = cpu, .ndim = 3, .dtype = f32,
                         .shape = y_mask_shape, .strides = NULL, .byte_offset = 0};

    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 0, &m_p_t), "get output 0");
    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 1, &logs_p_t), "get output 1");
    RUN(TVM_RT_WASM_RelaxVirtualMachineGetOutput(vm, NULL, 2, &y_mask_t), "get output 2");

    snprintf(path, sizeof(path), "%s/wasm_m_p_expanded.bin", dir);
    RUN(write_all(path, m_p_expanded, sizeof(m_p_expanded)), "write m_p_expanded");
    snprintf(path, sizeof(path), "%s/wasm_logs_p_expanded.bin", dir);
    RUN(write_all(path, logs_p_expanded, sizeof(logs_p_expanded)), "write logs_p_expanded");
    snprintf(path, sizeof(path), "%s/wasm_y_mask.bin", dir);
    RUN(write_all(path, y_mask, sizeof(y_mask)), "write y_mask");

    fprintf(stderr, "[encoder_test] first m_p values: %.6f %.6f %.6f %.6f\n",
            m_p_expanded[0], m_p_expanded[1], m_p_expanded[2], m_p_expanded[3]);
    fprintf(stderr, "[encoder_test] first y_mask values: %.6f %.6f %.6f %.6f\n",
            y_mask[0], y_mask[1], y_mask[2], y_mask[3]);

    TVM_RT_WASM_RelaxVirtualMachineFree(vm);
    return 0;
}
