#!/usr/bin/env python3
"""Emit a C stub that externs and registers every `__tvm_ffi_<name>`
kernel symbol exported by a compiled TIR object.

Cognition's Relax bytecode invokes TIR kernels by their bare short name
(e.g. `matmul`, `conv1d3`). TVM's system-lib code generator emits each
kernel as `__tvm_ffi_<name>`; the fork's system_library.c registers
whatever names get passed to `TVMBackendRegisterSystemLibSymbol`, then
`GetFunction` looks them up by exact match. So the driver has to bridge
prefix-stripped names -> prefixed symbol addresses.

For the 13.2 toy program (2 kernels) we hardcoded the bridge in
`test/toy_relax.c`. The encoder has ~100 kernels — this script reads
`llvm-nm` output for `lib0.o` and emits the extern list + a single
`register_all_kernels()` C function that calls
`TVMBackendRegisterSystemLibSymbol` for each name.

Runs at CMake configure time (or build time via `add_custom_command`).
Usage:
    python gen_kernel_stub.py <lib0.o> <output.c> <path-to-llvm-nm>
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


PREFIX = "__tvm_ffi_"
# Symbols we DON'T want to register as kernels — they have different
# semantics (context slot, blob) or are compiler-emitted helpers.
SKIP_EXACT = {"__tvm_ffi__library_ctx", "__tvm_ffi__library_bin"}


def main() -> int:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <lib0.o> <output.c> <llvm-nm>", file=sys.stderr)
        return 2
    obj = Path(sys.argv[1])
    out = Path(sys.argv[2])
    nm = sys.argv[3]

    result = subprocess.run([nm, str(obj)], capture_output=True, text=True, check=True)
    names: list[str] = []
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr, kind, sym = parts
        # Only take strong-defined text symbols (T). Weak (W) covers the
        # library_ctx var + compiler helpers we don't want.
        if kind != "T":
            continue
        if not sym.startswith(PREFIX):
            continue
        if sym in SKIP_EXACT:
            continue
        names.append(sym)
    names.sort()

    lines: list[str] = []
    lines.append("/* Auto-generated by test/gen_kernel_stub.py — do not edit. */")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("extern int TVMBackendRegisterSystemLibSymbol(const char *name, void *ptr);")
    lines.append("")
    for sym in names:
        lines.append(f"extern int {sym}(void *self, const void *args, int32_t n, void *result);")
    lines.append("")
    lines.append("/* Registers every TIR kernel exported by lib0.o under its bare short name")
    lines.append(" * (the name the Relax bytecode looks it up by). Returns 0 on success or the")
    lines.append(" * first non-zero status from the fork's TVMBackendRegisterSystemLibSymbol. */")
    lines.append("int register_all_encoder_kernels(void) {")
    lines.append("    int status;")
    for sym in names:
        bare = sym[len(PREFIX):]
        lines.append(f'    status = TVMBackendRegisterSystemLibSymbol("{bare}", (void *)&{sym});')
        lines.append("    if (status != 0) return status;")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    out.write_text("\n".join(lines))
    print(f"[gen_kernel_stub] wrote {out} with {len(names)} kernels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
