#!/usr/bin/env python3
"""Emit a C stub that externs and registers every `__tvm_ffi_<name>`
kernel symbol exported by a compiled TIR object.

Cognition's Relax bytecode invokes TIR kernels by their bare short name
(e.g. `matmul`, `conv1d3`). TVM's system-lib code generator emits each
kernel as `__tvm_ffi_<name>`; the fork's system_library.c registers
whatever names get passed to `TVMBackendRegisterSystemLibSymbol`, then
`GetFunction` looks them up by exact match. So the driver has to bridge
prefix-stripped names -> prefixed symbol addresses.

For the 13.2 toy program (2 kernels) we hardcoded the bridge in
`test/toy_relax.c`. The encoder has ~100 kernels — this script reads
`llvm-nm` output for `lib0.o` and emits the extern list + a single
`register_all_kernels()` C function that calls
`TVMBackendRegisterSystemLibSymbol` for each name.

Runs at CMake configure time (or build time via `add_custom_command`).
Usage:
    python gen_kernel_stub.py <lib0.o> <output.c> <path-to-llvm-nm>
        [--sys-lib-prefix=<PFX>] [--register-fn=<NAME>]

`--sys-lib-prefix` is the TVM `system_lib_prefix` attribute the
compiled module was built with (empty by default — the legacy no-prefix
shape). When set, the emitted stub:

  * Also emits `extern void *<PFX>__tvm_ffi__library_ctx;` — the weak
    context slot that lib0.o exports (renamed by TVM to include the
    prefix) — and registers it as `<PFX>__tvm_ffi__library_ctx` so the
    fork's SystemLibraryModuleCreateWithPrefix(<PFX>) can find it.
  * Registers each TIR kernel under `<PFX><bare>` (the Relax bytecode's
    lookup key — TVM's LLVM codegen also prefixes packed-func name
    strings inside the library_bin blob so they land as `<PFX><bare>`).

`--register-fn` overrides the emitted function name (default derived
from the prefix, or `register_all_encoder_kernels` when the prefix is
empty for historical compat).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


TVM_FFI_PREFIX = "__tvm_ffi_"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("obj", type=Path, help="lib0.o path")
    ap.add_argument("out", type=Path, help="output C stub path")
    ap.add_argument("nm", type=str, help="path to llvm-nm")
    ap.add_argument(
        "--sys-lib-prefix",
        default="",
        help="TVM system_lib_prefix used at compile time (default: empty).",
    )
    ap.add_argument(
        "--register-fn",
        default=None,
        help="C function name to emit (default derived from prefix).",
    )
    args = ap.parse_args()

    obj: Path = args.obj
    out: Path = args.out
    nm: str = args.nm
    sys_lib_prefix: str = args.sys_lib_prefix

    # For prefix="enc_", TVM's C-symbol layout is:
    #   * library_bin:  enc___tvm_ffi__library_bin  (prefix outside)
    #   * library_ctx:  enc___tvm_ffi__library_ctx  (prefix outside)
    #   * kernel `add`: __tvm_ffi_enc_add           (prefix inside, after __tvm_ffi_)
    # And the bytecode inside library_bin refers to kernels by `enc_add`
    # (short name with the same prefix), which is what we want to
    # register in the trie.
    library_bin_sym = f"{sys_lib_prefix}__tvm_ffi__library_bin"
    library_ctx_sym = f"{sys_lib_prefix}__tvm_ffi__library_ctx"
    skip_exact = {library_bin_sym, library_ctx_sym}

    result = subprocess.run([nm, str(obj)], capture_output=True, text=True, check=True)
    names: list[str] = []
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr, kind, sym = parts
        # Only take strong-defined text symbols (T). Weak (W) covers the
        # library_ctx var + compiler helpers we don't want.
        if kind != "T":
            continue
        if not sym.startswith(TVM_FFI_PREFIX):
            continue
        if sym in skip_exact:
            continue
        names.append(sym)
    names.sort()

    if args.register_fn:
        register_fn = args.register_fn
    elif sys_lib_prefix:
        # Strip trailing underscore for readability.
        register_fn = f"register_all_{sys_lib_prefix.rstrip('_')}_kernels"
    else:
        register_fn = "register_all_encoder_kernels"

    lines: list[str] = []
    lines.append("/* Auto-generated by test/gen_kernel_stub.py — do not edit. */")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("extern int TVMBackendRegisterSystemLibSymbol(const char *name, void *ptr);")
    lines.append("")
    if sys_lib_prefix:
        # Weak symbol declared by lib0.o.
        lines.append(f"extern void *{library_ctx_sym};")
        lines.append("")
    for sym in names:
        lines.append(f"extern int {sym}(void *self, const void *args, int32_t n, void *result);")
    lines.append("")
    lines.append(
        "/* Registers every TIR kernel exported by lib0.o under the name the Relax bytecode looks"
    )
    lines.append(
        " * up (bare short name for legacy no-prefix modules, prefixed short name for M13.7"
    )
    lines.append(
        " * multi-model wasm variants). Also registers the library_ctx slot when a prefix is set."
    )
    lines.append(
        " * Returns 0 on success or the first non-zero status from TVMBackendRegisterSystemLibSymbol."
    )
    lines.append(" */")
    lines.append(f"int {register_fn}(void) {{")
    lines.append("    int status;")
    if sys_lib_prefix:
        lines.append(
            f'    status = TVMBackendRegisterSystemLibSymbol("{library_ctx_sym}", (void *)&{library_ctx_sym});'
        )
        lines.append("    if (status != 0) return status;")
    for sym in names:
        bare = sym[len(TVM_FFI_PREFIX):]  # e.g. `enc_add`
        lines.append(f'    status = TVMBackendRegisterSystemLibSymbol("{bare}", (void *)&{sym});')
        lines.append("    if (status != 0) return status;")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    out.write_text("\n".join(lines))
    print(f"[gen_kernel_stub] wrote {out} with {len(names)} kernels (prefix={sys_lib_prefix!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
